### ISSUE TITLE
Hook error disguises previous build error

### ISSUE THREAD

**Issue by tirsen** [buildkite-plugins/test-collector-buildkite-plugin#10]
If an earlier step fails (for example due to a compilation error) then the hook will give an error message and the user thinks it's this hook that has failed.

```
$ /plugins/github-com-buildkite-plugins-test-collector-buildkite-plugin-v1-0-0/hooks/pre-exit
No files found matching '**/out/test-results/**/*.xml'
🚨 Error: Error tearing down bootstrap: The plugin test-collector pre-exit hook exited with status 1
```

I'm still a buildkite noob. Can a plugin hook know the exit code of a previous step? In that case I think it should not fail with the "No files found" error. (It should still try to upload any files it finds of course, we want to submit failed test runs as well.)

It needs to return the error code from the original build error as we use that for retry logic.

**Comment by mrdailey99** [comment]
@tirsen Yea I am not sure what the plugin is doing... I get the same output in my pipeline (even though it runs successfully up until the plugin portion)
<html>
<body>


Running plugin test-collector pre-exit hook | 0s
-- | --
  | > C:\buildkite-agent\plugins\github-com-buildkite-plugins-test-collector-buildkite-plugin-v1-0-0\hooks\pre-exit
  | 🚨 Error: Error tearing down bootstrap: The plugin test-collector pre-exit hook exited with status 1


</body>
</html>
I have my plugin snippet configured like so:
```
    plugins:
      - test-collector#v1.0.0:
          files: "${BUILDKITE_BUILD_CHECKOUT_PATH}/ProvarProject/ANT/Results/JUnit.xml"
          format: "junit"
          debug: true
```
I don't know if the "debug: true" actually produces any additional output here unfortunately.
