### ISSUE TITLE
Support absolute paths

### ISSUE THREAD

**Issue by djudd** [buildkite-plugins/test-collector-buildkite-plugin#38]
We have some code which sticks our JUnit XML in `/tmp/junit.xml`. I can't use the test-collector to upload this as-is because a `./` is always prefixed to the path. I'm not sure why that is, but it'd be nice to at least have like an `absolute_path` option which avoids doing that.

**Comment by toote** [comment]
That is a great idea! I created PR #39 with this functionality :)
