### ISSUE TITLE
Nested JUnit testsuite causes duplication

### ISSUE THREAD

**Issue by tristankenney** [buildkite-plugins/test-collector-buildkite-plugin#54]
Hi folks! 

We've run into a problem where nested testsuites – i.e. `<testsuite>`s within `<testsuite>`s cause duplication in the Buildkite interface. 

So this JUnit.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Full Suite" tests="1" assertions="6" errors="0" warnings="1" failures="0" skipped="5" time="0.03">
    <testsuite name="Unit Tests" tests="1" assertions="6" errors="0" warnings="0" failures="0" skipped="0" time="0.03">
      <testsuite name="DuplicatedTest" file="/app/tests/DuplicatedTest.php" tests="1" assertions="6" errors="0" warnings="0" failures="0" skipped="0" time="0.03">
        <testcase name="testcase1" class="DuplicatedTest" classname="DuplicatedTest" file="/app/trunk/application/tests/validator/DuplicatedTest.php" line="115" assertions="2" time="0.01"/>
        <testcase name="testcase2" class="DuplicatedTest" classname="DuplicatedTest" file="/app/trunk/application/tests/validator/DuplicatedTest.php" line="115" assertions="2" time="0.01"/>
        <testcase name="testcase3" class="DuplicatedTest" classname="DuplicatedTest" file="/app/trunk/application/tests/validator/DuplicatedTest.php" line="115" assertions="2" time="0.01"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```

will result in this duplication:

![image](https://github.com/buildkite-plugins/test-collector-buildkite-plugin/assets/424100/0b5f2764-a6fc-40bc-a8f4-ec9b67f38c0c)

whereas when the outer testsuites are removed, there's no duplication:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="DuplicatedTest" file="/app/tests/DuplicatedTest.php" tests="1" assertions="6" errors="0" warnings="0" failures="0" skipped="0" time="0.03">
    <testcase name="testcase1" class="DuplicatedTest" classname="DuplicatedTest" file="/app/trunk/application/tests/validator/DuplicatedTest.php" line="115" assertions="2" time="0.01"/>
    <testcase name="testcase2" class="DuplicatedTest" classname="DuplicatedTest" file="/app/trunk/application/tests/validator/DuplicatedTest.php" line="115" assertions="2" time="0.01"/>
    <testcase name="testcase3" class="DuplicatedTest" classname="DuplicatedTest" file="/app/trunk/application/tests/validator/DuplicatedTest.php" line="115" assertions="2" time="0.01"/>
  </testsuite>
</testsuites>
```
![image](https://github.com/buildkite-plugins/test-collector-buildkite-plugin/assets/424100/fbf36235-6141-434b-b30c-90e6f16dc062)

NB: This is the plugin we're using to perform in upload in the pipeline, but happy to move this issue to another repo if it makes more sense.

**Comment by tristankenney** [comment]
> Hey @tristankenney! Thanks for all your detailed info! 🙏🏻
> This is interesting! I'm not sure it's a problem with the plugin yet 🤔. Can you also try using curl directly (https://buildkite.com/docs/test-analytics/importing-junit-xml#how-to-import-junit-xml-in-buildkite-not-using-a-plugin). So we can narrow this thing down :)  Thanks! 

Hi @pzeballos! That was the one piece of key info I forgot — it occurs with curl as well.

**Comment by pzeballos** [comment]
Thanks @tristankenney! I'll raise it with our TA team, as it doesn't seem to be an issue with the plugin 🙂

**Comment by pzeballos** [comment]
Hey @tristankenney! The TA team shipped a fix for this, can you confirm if it's working as expected? Thanks!

**Comment by pzeballos** [comment]
hey @tristankenney! This issue should be resolved, let us know if that is not the case :) Thanks for bringing this up!
