### ISSUE TITLE
Annotation printing `\n` instead of newlines

### ISSUE THREAD

**Issue by donallfg** [buildkite-plugins/test-collector-buildkite-plugin#59]
We've enabled the annotation-link on the test-collector plugin. 
The annotation appears like this:

![image](https://github.com/buildkite-plugins/test-collector-buildkite-plugin/assets/80103069/a15ed595-a3e9-4987-bee3-c40ef7364465)

We would expect it to be (I've manually edited the annotation)
![image](https://github.com/buildkite-plugins/test-collector-buildkite-plugin/assets/80103069/a2aaa301-000c-4d34-a81e-c856574b72ed)

Our agent is running on ubuntu 20.04, if that helps?

**Comment by pzeballos** [comment]
Thanks for raising it @donallfg! we merged a fix #61  and we'll do a release this week :)
