### ISSUE TITLE
Performance of test-collector is unacceptably slow.

### ISSUE THREAD

**Issue by donallfg** [buildkite-plugins/test-collector-buildkite-plugin#60]
Hi! As per our other issue, we enabled the test collecter recently. We started with a smaller project and were very happy with the results so we enabled it on our "main" project.

According to Test Analytics, we have just shy of 10k tests, generated from  and it takes ~2.5 minutes to run them.  Using the test-collector plugin, it's taking over 8 minutes to upload the tests, from ~500 junit xml files. This is actually longer than the rest of our pipeline takes to run.

**Comment by pzeballos** [comment]
Hey @donallfg! In the latest release ([v1.9.0](https://github.com/buildkite-plugins/test-collector-buildkite-plugin/releases/tag/v1.9.0)), we added the feature of uploading multiple files in parallel, which improves the overall performance in those cases. You can try it with the [upload-concurrency](https://github.com/buildkite-plugins/test-collector-buildkite-plugin#upload-concurrencynumber) option.

**Comment by donallfg** [comment]
Oh thanks! We were using 1.8.

I've updated and set it to 100, we're now seeing 20 seconds. It still feels a bit long but I'll play with the numbers and see. Thanks!
